spring.application.name=spring-security-demo

server.servlet.session.cookie.same-site=strict

spring.datasource.url = jdbc:postgresql://localhost:5432/daniemodu
spring.datasource.username = postgres
spring.datasource.password =0507


